/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author 52811
 */
public class FormatoBuscaMinas extends javax.swing.JFrame 
{
    int nFilas = 10;
    int nColumnas = 10;
    int nMinas = 10;
    
    JButton[][] botones;
    
    TableroBuscaMinas tableroBuscaMinas;
    
    public FormatoBuscaMinas() 
    {
        initComponents();
        cargaControles();
        crearTableroBuscaminas();
    }
    private void crearTableroBuscaminas()
    {
        tableroBuscaMinas = new TableroBuscaMinas(nFilas, nColumnas, nMinas);
        tableroBuscaMinas.setPartidaPerdida(new Consumer<List<Casillas>>() 
        {
            @Override
            public void accept(List<Casillas> t)
            {
                for(Casillas casillasMinas: t)
                {
                    botones[casillasMinas.getPosicionF()][casillasMinas.getPosicionC()].setText("*");
                }
            }
        });
        
        tableroBuscaMinas.imprimirTablero();
        
        
        
        tableroBuscaMinas.setEventoPartidaGanada(new Consumer<List<Casillas>>() 
        {
            @Override
            public void accept(List<Casillas> t)
            {
                for(Casillas casillasMinas: t)
                {
                    botones[casillasMinas.getPosicionF()][casillasMinas.getPosicionC()].setText(":)");
                }
            }
        });
        tableroBuscaMinas.setCasillaAbierta(new Consumer<Casillas>()
        {
            @Override
            public void accept(Casillas t)
            {
                botones[t.getPosicionF()][t.getPosicionC()].setEnabled(false);
                botones[t.getPosicionF()][t.getPosicionC()].setText(t.getnMinasAlrededor()==0?"":t.getnMinasAlrededor()+"");
            }
        });
    }
    private void cargaControles()
    {
        int posX = 25;
        int posY = 25;
        int anchoControles = 30;
        int altoControles = 30;
        
        botones = new JButton[nFilas][nColumnas];
        for(int i = 0 ; i < botones.length ; i++)
        {
            for(int j = 0 ; j < botones[i].length ; j++)
            {
                botones[i][j] = new JButton();
                botones[i][j].setName(i+","+j);
                botones[i][j].setBorder(null);
                if(i == 0 && j == 0)
                {
                    botones[i][j].setBounds(posX, posY, anchoControles, 
                    altoControles);
                }
                else if(i == 0 && j != 0)
                {
                    botones[i][j].setBounds(botones[i][j-1].getX()+ botones[i][j-1].getWidth(),posY, anchoControles, 
                    altoControles);
                }
                else
                {
                    botones[i][j].setBounds(botones[i-1][j].getX(),botones[i-1][j].getY()+ botones[i-1][j].getHeight(), anchoControles, 
                    altoControles);
                }
                botones[i][j].addActionListener(new ActionListener() 
                {
                    @Override
                    public void actionPerformed(ActionEvent e) 
                    {
                        btnClick(e);
                    }
                });
                        
                getContentPane().add(botones[i][j]);
            }
        }
    }
    private void btnClick(ActionEvent e)
    {
        JButton btn = (JButton)e.getSource();
        String[] coordenada = btn.getName().split(",");
        int posFila = Integer.parseInt(coordenada[0]);
        int posColumna = Integer.parseInt(coordenada[1]);
        JOptionPane.showMessageDialog(rootPane, posFila+","+posColumna);
        tableroBuscaMinas.seleccionarCasilla(posFila, posColumna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormatoBuscaMinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormatoBuscaMinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormatoBuscaMinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormatoBuscaMinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormatoBuscaMinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
